[package]
name = "rusty-smith-example"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-smith = { path = "../../crates/rusty_smith" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "generate_smithy"
path = "src/main.rs"
