[package]
name = "superposition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = { version = "0.6" }
actix-web = { workspace = true }
cac_toml = { path = "../cac_toml" }
cfg-if = { workspace = true }
context_aware_config = { path = "../context_aware_config" }
dotenv = "0.15.0"
env_logger = "0.8"
experimentation_platform = { path = "../experimentation_platform" }
fred = { workspace = true, optional = true }
frontend = { path = "../frontend" }
futures-util = "0.3.31"
jsonwebtoken = "9.3.0"
leptos = { workspace = true }
leptos_actix = { version = "0.6.11" }
openidconnect = "3.5.0"
reqwest = { workspace = true }
rs-snowflake = { workspace = true }
samael = { version = "0.0.17", features = ["xmlsec"] }
serde.workspace = true
serde_json.workspace = true
service_utils = { path = "../service_utils" }
superposition_types = { path = "../superposition_types" }
toml = { workspace = true }
url = "2.5.4"

[features]
high-performance-mode = [
    "context_aware_config/high-performance-mode",
    "service_utils/high-performance-mode",
    "dep:fred",
]

[lints]
workspace = true
