[package]
name = "cac_toml_app_example"
description = "cac_toml_app_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cac_toml = { git = "https://github.com/juspay/superposition.git", branch = "main" }
clap = { version = "4.3.0", features = ["derive"] }
toml = { version = "0.8.8", features = ["preserve_order"] }
