apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "superposition.fullname" . }}-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superposition.labels" . | nindent 4 }}
data:
{{- include "superposition.configsToData" . | nindent 2 }}

