apiVersion: v1
kind: Secret
metadata:
  name: {{ include "superposition.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "superposition.labels" . | nindent 4 }}
type: Opaque
data:
{{- include "superposition.secretsToData" . | nindent 2 }}
