apiVersion: v1
kind: Service
metadata:
  name: {{ include "superposition.fullname" . }}
  labels:
    {{- include "superposition.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: http
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "superposition.selectorLabels" . | nindent 4 }}
