[package]
name = "superposition-demo-app"
description = "superposition-demo-app"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6"
actix-web = "4"
awc = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
