[package]
name = "superposition-demo-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-files = "0.6"
awc = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tera = "1.11"
