[package]
name = "cac_client_integration_example"
description = "cac_client_integration_example"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { workspace = true }
cac_client = { path = "../../crates/cac_client" }
serde_json = { workspace = true }


[lints]
workspace = true
