[package]
name = "superposition_macros"
description = "macros used in the superposition code-base"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true
